env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - "@typescript-eslint"
  #- "mocha-no-only"
rules: {
  "mocha-no-only/mocha-no-only": "error"
}
